import type { WorkbenchLayout, LayoutBreakpoints, PanelId } from '../types/layout';

export const LAYOUT_PRESETS: Record<string, WorkbenchLayout> = {
  guided: {
    id: 'guided',
    name: 'Guided Learning',
    description: 'Optimized for beginners with clear visual hierarchy and helpful panels',
    panels: {
      nodePanel: {
        id: 'nodePanel',
        title: 'Node Library',
        visible: true,
        minimized: false,
        size: { width: 280, minWidth: 240, maxWidth: 400 },
        position: 'left',
        resizable: true,
        closable: false,
        order: 1,
      },
      nodeEditor: {
        id: 'nodeEditor',
        title: 'Node Graph',
        visible: true,
        minimized: false,
        size: { height: '65%', minHeight: 200 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 2,
      },
      viewport3d: {
        id: 'viewport3d',
        title: '3D Viewport',
        visible: true,
        minimized: false,
        size: { height: '35%', minHeight: 200 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 3,
      },
      inspector: {
        id: 'inspector',
        title: 'Properties',
        visible: true,
        minimized: false,
        size: { width: 320, minWidth: 280, maxWidth: 450 },
        position: 'right',
        resizable: true,
        closable: true,
        order: 4,
      },
      console: {
        id: 'console',
        title: 'Console',
        visible: false,
        minimized: true,
        size: { height: 120, minHeight: 80, maxHeight: 300 },
        position: 'bottom',
        resizable: true,
        closable: true,
        order: 5,
      },
      toolbar: {
        id: 'toolbar',
        title: 'Toolbar',
        visible: true,
        minimized: false,
        size: { height: 48, minHeight: 48, maxHeight: 48 },
        position: 'top',
        resizable: false,
        closable: false,
        order: 0,
      },
    },
    layout: {
      type: 'container',
      id: 'root',
      size: 100,
      direction: 'row',
      children: [
        {
          type: 'panel',
          id: 'nodePanel',
          size: 280,
          minSize: 240,
          maxSize: 400,
        },
        {
          type: 'container',
          id: 'mainArea',
          size: 100,
          direction: 'column',
          children: [
            {
              type: 'panel',
              id: 'nodeEditor',
              size: 65,
              minSize: 30,
              maxSize: 85,
            },
            {
              type: 'panel',
              id: 'viewport3d',
              size: 35,
              minSize: 15,
              maxSize: 70,
            },
          ],
        },
        {
          type: 'panel',
          id: 'inspector',
          size: 320,
          minSize: 280,
          maxSize: 450,
        },
      ],
    },
    metadata: {
      created: new Date(),
      modified: new Date(),
      isDefault: true,
      screenSize: 'desktop',
      version: '1.0.0',
    },
  },

  professional: {
    id: 'professional',
    name: 'Professional',
    description: 'Maximum screen utilization for experienced users with all panels visible',
    panels: {
      nodePanel: {
        id: 'nodePanel',
        title: 'Node Library',
        visible: true,
        minimized: false,
        size: { width: 240, minWidth: 200, maxWidth: 350 },
        position: 'left',
        resizable: true,
        closable: true,
        order: 1,
      },
      nodeEditor: {
        id: 'nodeEditor',
        title: 'Node Graph',
        visible: true,
        minimized: false,
        size: { height: '70%', minHeight: 250 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 2,
      },
      viewport3d: {
        id: 'viewport3d',
        title: '3D Viewport',
        visible: true,
        minimized: false,
        size: { height: '30%', minHeight: 150 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 3,
      },
      inspector: {
        id: 'inspector',
        title: 'Properties',
        visible: true,
        minimized: false,
        size: { width: 280, minWidth: 250, maxWidth: 400 },
        position: 'right',
        resizable: true,
        closable: true,
        order: 4,
      },
      console: {
        id: 'console',
        title: 'Console',
        visible: true,
        minimized: false,
        size: { height: 120, minHeight: 80, maxHeight: 250 },
        position: 'bottom',
        resizable: true,
        closable: true,
        order: 5,
      },
      toolbar: {
        id: 'toolbar',
        title: 'Toolbar',
        visible: true,
        minimized: false,
        size: { height: 48, minHeight: 48, maxHeight: 48 },
        position: 'top',
        resizable: false,
        closable: false,
        order: 0,
      },
    },
    layout: {
      type: 'container',
      id: 'root',
      size: 100,
      direction: 'row',
      children: [
        {
          type: 'panel',
          id: 'nodePanel',
          size: 240,
          minSize: 200,
          maxSize: 350,
        },
        {
          type: 'container',
          id: 'mainArea',
          size: 100,
          direction: 'column',
          children: [
            {
              type: 'panel',
              id: 'nodeEditor',
              size: 70,
              minSize: 40,
              maxSize: 85,
            },
            {
              type: 'panel',
              id: 'viewport3d',
              size: 30,
              minSize: 15,
              maxSize: 60,
            },
          ],
        },
        {
          type: 'panel',
          id: 'inspector',
          size: 280,
          minSize: 250,
          maxSize: 400,
        },
      ],
    },
    metadata: {
      created: new Date(),
      modified: new Date(),
      isDefault: false,
      screenSize: 'desktop',
      version: '1.0.0',
    },
  },

  modeling: {
    id: 'modeling',
    name: 'Modeling Focus',
    description: 'Emphasized 3D viewport for geometric modeling with minimal distractions',
    panels: {
      nodePanel: {
        id: 'nodePanel',
        title: 'Node Library',
        visible: true,
        minimized: true,
        size: { width: 60, minWidth: 60, maxWidth: 300 },
        position: 'left',
        resizable: true,
        closable: true,
        order: 1,
      },
      nodeEditor: {
        id: 'nodeEditor',
        title: 'Node Graph',
        visible: true,
        minimized: false,
        size: { height: '40%', minHeight: 150 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 2,
      },
      viewport3d: {
        id: 'viewport3d',
        title: '3D Viewport',
        visible: true,
        minimized: false,
        size: { height: '60%', minHeight: 300 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 3,
      },
      inspector: {
        id: 'inspector',
        title: 'Properties',
        visible: true,
        minimized: false,
        size: { width: 300, minWidth: 280, maxWidth: 400 },
        position: 'right',
        resizable: true,
        closable: true,
        order: 4,
      },
      console: {
        id: 'console',
        title: 'Console',
        visible: false,
        minimized: true,
        size: { height: 100, minHeight: 80, maxHeight: 200 },
        position: 'bottom',
        resizable: true,
        closable: true,
        order: 5,
      },
      toolbar: {
        id: 'toolbar',
        title: 'Toolbar',
        visible: true,
        minimized: false,
        size: { height: 48, minHeight: 48, maxHeight: 48 },
        position: 'top',
        resizable: false,
        closable: false,
        order: 0,
      },
    },
    layout: {
      type: 'container',
      id: 'root',
      size: 100,
      direction: 'row',
      children: [
        {
          type: 'panel',
          id: 'nodePanel',
          size: 60,
          minSize: 60,
          maxSize: 300,
        },
        {
          type: 'container',
          id: 'mainArea',
          size: 100,
          direction: 'column',
          children: [
            {
              type: 'panel',
              id: 'nodeEditor',
              size: 40,
              minSize: 20,
              maxSize: 70,
            },
            {
              type: 'panel',
              id: 'viewport3d',
              size: 60,
              minSize: 30,
              maxSize: 80,
            },
          ],
        },
        {
          type: 'panel',
          id: 'inspector',
          size: 300,
          minSize: 280,
          maxSize: 400,
        },
      ],
    },
    metadata: {
      created: new Date(),
      modified: new Date(),
      isDefault: false,
      screenSize: 'desktop',
      version: '1.0.0',
    },
  },

  nodeFocused: {
    id: 'nodeFocused',
    name: 'Node Development',
    description: 'Maximized node editor for complex graph development and scripting',
    panels: {
      nodePanel: {
        id: 'nodePanel',
        title: 'Node Library',
        visible: true,
        minimized: false,
        size: { width: 320, minWidth: 280, maxWidth: 450 },
        position: 'left',
        resizable: true,
        closable: true,
        order: 1,
      },
      nodeEditor: {
        id: 'nodeEditor',
        title: 'Node Graph',
        visible: true,
        minimized: false,
        size: { height: '85%', minHeight: 400 },
        position: 'center',
        resizable: true,
        closable: false,
        order: 2,
      },
      viewport3d: {
        id: 'viewport3d',
        title: '3D Viewport',
        visible: true,
        minimized: false,
        size: { height: '15%', minHeight: 120 },
        position: 'center',
        resizable: true,
        closable: true,
        order: 3,
      },
      inspector: {
        id: 'inspector',
        title: 'Properties',
        visible: true,
        minimized: false,
        size: { width: 350, minWidth: 300, maxWidth: 500 },
        position: 'right',
        resizable: true,
        closable: true,
        order: 4,
      },
      console: {
        id: 'console',
        title: 'Console',
        visible: true,
        minimized: false,
        size: { height: 100, minHeight: 80, maxHeight: 200 },
        position: 'bottom',
        resizable: true,
        closable: true,
        order: 5,
      },
      toolbar: {
        id: 'toolbar',
        title: 'Toolbar',
        visible: true,
        minimized: false,
        size: { height: 48, minHeight: 48, maxHeight: 48 },
        position: 'top',
        resizable: false,
        closable: false,
        order: 0,
      },
    },
    layout: {
      type: 'container',
      id: 'root',
      size: 100,
      direction: 'row',
      children: [
        {
          type: 'panel',
          id: 'nodePanel',
          size: 320,
          minSize: 280,
          maxSize: 450,
        },
        {
          type: 'container',
          id: 'mainArea',
          size: 100,
          direction: 'column',
          children: [
            {
              type: 'panel',
              id: 'nodeEditor',
              size: 85,
              minSize: 60,
              maxSize: 95,
            },
            {
              type: 'panel',
              id: 'viewport3d',
              size: 15,
              minSize: 5,
              maxSize: 40,
            },
          ],
        },
        {
          type: 'panel',
          id: 'inspector',
          size: 350,
          minSize: 300,
          maxSize: 500,
        },
      ],
    },
    metadata: {
      created: new Date(),
      modified: new Date(),
      isDefault: false,
      screenSize: 'desktop',
      version: '1.0.0',
    },
  },
};

export const LAYOUT_BREAKPOINTS: LayoutBreakpoints = {
  mobile: {
    maxWidth: 768,
    defaultLayout: 'guided',
    hiddenPanels: ['console', 'inspector'],
    adaptations: {
      nodePanel: { size: { width: '100%' }, position: 'bottom' },
      nodeEditor: { size: { height: '70%' } },
      viewport3d: { size: { height: '30%' } },
    },
  },
  tablet: {
    maxWidth: 1024,
    defaultLayout: 'guided',
    hiddenPanels: ['console'],
    adaptations: {
      nodePanel: { size: { width: 220 } },
      inspector: { size: { width: 280 } },
    },
  },
  desktop: {
    maxWidth: 1920,
    defaultLayout: 'guided',
    hiddenPanels: [],
    adaptations: {},
  },
  ultrawide: {
    maxWidth: Infinity,
    defaultLayout: 'professional',
    hiddenPanels: [],
    adaptations: {
      nodePanel: { size: { width: 350 } },
      inspector: { size: { width: 400 } },
    },
  },
};

export const getDefaultLayoutForScreenSize = (screenSize: string): WorkbenchLayout => {
  const breakpoint = LAYOUT_BREAKPOINTS[screenSize as keyof typeof LAYOUT_BREAKPOINTS];
  if (breakpoint && LAYOUT_PRESETS[breakpoint.defaultLayout]) {
    return LAYOUT_PRESETS[breakpoint.defaultLayout] as WorkbenchLayout;
  }
  return LAYOUT_PRESETS.guided as WorkbenchLayout;
};

export const getScreenSizeFromWidth = (width: number): keyof LayoutBreakpoints => {
  if (width <= LAYOUT_BREAKPOINTS.mobile.maxWidth) return 'mobile';
  if (width <= LAYOUT_BREAKPOINTS.tablet.maxWidth) return 'tablet';
  if (width <= LAYOUT_BREAKPOINTS.desktop.maxWidth) return 'desktop';
  return 'ultrawide';
};
