#!/bin/bash

# Script to create Horizon A: Geometry Hardening milestone in GitHub
# Run this script locally with: ./scripts/create-horizon-a-milestone.sh

set -e

echo "Creating Horizon A: Geometry Hardening milestone..."

gh milestone create "Horizon A: Geometry Hardening" \
  --description "Complete OCCT pipeline optimization and geometry reliability improvements.

Building on completed Horizon 0 (Security & Quality Hardening), this milestone focuses on:

1. **OCCT Performance & Recovery**: Performance profiling, operation diagnostics, error recovery, memory optimization
2. **CLI & Studio Alignment**: Unified GeometryAPI, remove mock fallbacks, structured error propagation
3. **Mock Geometry Teardown**: Complete removal of MockGeometry, OCCT-only execution, test fixtures
4. **Autogenerated Node Catalogue**: Fix generator, compile 1012+ nodes, validation framework, palette integration
5. **Type Safety & Artifact Hygiene**: Strict TypeScript, lint enforcement, artifact cleanup, OCCT docs

**Timeline**: 12 weeks (Q1 2026)
**Target Completion**: March 31, 2026

See \`docs/project/HORIZON_A_GEOMETRY_HARDENING.md\` for detailed roadmap and \`docs/project/HORIZON_A_GITHUB_ISSUES.md\` for issue templates." \
  --due-date "2026-03-31"

echo ""
echo "✅ Milestone created successfully!"
echo ""
echo "Next steps:"
echo "1. Create the 19 GitHub issues using the templates in docs/project/HORIZON_A_GITHUB_ISSUES.md"
echo "2. Assign issues to the milestone"
echo "3. Add appropriate labels to each issue"
echo "4. Assign issues to team members"
echo ""
echo "You can also use: ./scripts/create-horizon-a-issues.sh to create all issues"
